// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZANIKlt-7pHLvTB09djgY7T23MZM91I',
    appId: '1:365756037634:web:870c7345c2473b282ec51b',
    messagingSenderId: '365756037634',
    projectId: 'prakflutterfirebase-adfe5',
    authDomain: 'prakflutterfirebase-adfe5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-adfe5.appspot.com',
    measurementId: 'G-7QW6EHMGXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJH-EnbF4Gx5uvPdK7fn7AQf5yhk8D1f0',
    appId: '1:365756037634:android:5f89a09f1c2f46be2ec51b',
    messagingSenderId: '365756037634',
    projectId: 'prakflutterfirebase-adfe5',
    storageBucket: 'prakflutterfirebase-adfe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUzhCrHS3hn2XwDGZTGBEu_WVCYEkWlLw',
    appId: '1:365756037634:ios:d9681ad645bc58282ec51b',
    messagingSenderId: '365756037634',
    projectId: 'prakflutterfirebase-adfe5',
    storageBucket: 'prakflutterfirebase-adfe5.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUzhCrHS3hn2XwDGZTGBEu_WVCYEkWlLw',
    appId: '1:365756037634:ios:d9681ad645bc58282ec51b',
    messagingSenderId: '365756037634',
    projectId: 'prakflutterfirebase-adfe5',
    storageBucket: 'prakflutterfirebase-adfe5.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSZANIKlt-7pHLvTB09djgY7T23MZM91I',
    appId: '1:365756037634:web:ade98605052a8a042ec51b',
    messagingSenderId: '365756037634',
    projectId: 'prakflutterfirebase-adfe5',
    authDomain: 'prakflutterfirebase-adfe5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-adfe5.appspot.com',
    measurementId: 'G-P83EPJD97K',
  );
}
