// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMkZQWq3ffFbhUbfD06z7nEMd_D1zyrfI',
    appId: '1:1000529219325:web:e21439451cadad5e2eb894',
    messagingSenderId: '1000529219325',
    projectId: 'ppb2266',
    authDomain: 'ppb2266.firebaseapp.com',
    storageBucket: 'ppb2266.appspot.com',
    measurementId: 'G-6G96TPMB8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-fXIOoy-MkUIaTdgWRRnVHKR4Q1I7n0',
    appId: '1:1000529219325:android:65200441ff0251cf2eb894',
    messagingSenderId: '1000529219325',
    projectId: 'ppb2266',
    storageBucket: 'ppb2266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIczK9IGxEgxMAD9KCebUdc8J_SD8Pprk',
    appId: '1:1000529219325:ios:23d526dff8b9e1842eb894',
    messagingSenderId: '1000529219325',
    projectId: 'ppb2266',
    storageBucket: 'ppb2266.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIczK9IGxEgxMAD9KCebUdc8J_SD8Pprk',
    appId: '1:1000529219325:ios:23d526dff8b9e1842eb894',
    messagingSenderId: '1000529219325',
    projectId: 'ppb2266',
    storageBucket: 'ppb2266.appspot.com',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMkZQWq3ffFbhUbfD06z7nEMd_D1zyrfI',
    appId: '1:1000529219325:web:9e24ad776623dceb2eb894',
    messagingSenderId: '1000529219325',
    projectId: 'ppb2266',
    authDomain: 'ppb2266.firebaseapp.com',
    storageBucket: 'ppb2266.appspot.com',
    measurementId: 'G-2XWZLECJ4J',
  );

}